linters-settings:
  gocyclo:
    min-complexity: 25
  govet:
    check-shadowing: false
  misspell:
    locale: "US"

linters:
  enable-all: true
  disable:
    - stylecheck
    - gosec
    - dupl
    - depguard
    - lll
    - prealloc
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    # These are deprecated
    - execinquery
    - exportloopref
    - gomnd
