linters-settings:
  gocyclo:
    min-complexity: 25
  govet:
    check-shadowing: true
  misspell:
    locale: "US"

linters:
  enable-all: true
  disable:
    - golint
    - stylecheck
    - gosec
    - dupl
    - maligned
    - depguard
    - lll
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - gochecknoglobals
